name: Build and Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --no-build -c Release -o out
      
    - name: Verifica si la clave API de NuGet está configurada
      run: if [ -z "${{ secrets.NUGET_TOKEN }}" ]; then echo "NUGET_API_KEY no está configurada"; else echo "NUGET_API_KEY está configurada"; fi

    - name: Push NuGet Package
      run: dotnet nuget push out/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json


